### ISSUE TITLE
主题样式问题

### ISSUE THREAD

**Issue by crowyyyy** [ttkican/Blog#3]
请问是怎么样将butterfly或者shoka的源码中把页面设计样式从hexo框架中抽离出来加入自己的项目的？

**Comment by ttkican** [comment]
找到他们的源码中的css文件夹

**Comment by crowyyyy** [comment]
抱歉我可能没表达清楚，类似于butterfly源码中的pug文件，你是如何将其转化为你项目中vue文件中的某些部分的呢

**Comment by ttkican** [comment]
我直接是浏览器F12参考他们的样式来做的
